### PR TITLE
fix: Use imports to detect GNOME environment

### LINKED ISSUE #1706: Doesn't work remote mouse and keyboard
### Describe the bug

After updating to GNOME 45, remote mouse and keyboard doesn't work.

### Steps to reproduce

1. Have Manjaro with GNOME 44
2. Update to GNOME 45

### Expected behavior

Working remote mouse and keyboard

### GSConnect version

56

### Installed from

GNOME Extensions website

### GNOME Shell version

45.0

### Linux distribution/release

Manjaro 23.0.4

### Paired device(s)

Redmi note 8 pro

### KDE Connect app version

1.29.0

### Plugin(s)

_No response_

### Support log

```plain text
GSConnect: 56 (user)
GJS:       17800
Session:   x11
OS:        Manjaro Linux
--------------------------------------------------------------------------------
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.743Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15714
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.743Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 3c50427d-c260-40cd-bdac-89105ce6bb5d; GetAppSettings
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.744Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 4a3df1ca-d1f4-4caa-bf68-b621538599b5; GetAccount
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.744Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 4a3df1ca-d1f4-4caa-bf68-b621538599b5; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.744Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 8846e77a-696e-4e73-b262-32a83235cb6f; GetDaemonStatus
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.744Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.744Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.744Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 8846e77a-696e-4e73-b262-32a83235cb6f; Success
ноя 06 17:24:00 warp-svc[661]: 2023-11-06T15:24:00.744Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:01 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:01 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.747Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15718
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 42e87b69-34a0-48bb-a471-d8708af856e1; GetAppSettings
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 661924a3-143e-48f2-9502-6e9c8b94252e; GetAccount
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 661924a3-143e-48f2-9502-6e9c8b94252e; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.748Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 8f24d67c-c8f2-4afc-a649-54430405dfa3; GetDaemonStatus
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.748Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.748Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.748Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 8f24d67c-c8f2-4afc-a649-54430405dfa3; Success
ноя 06 17:24:01 warp-svc[661]: 2023-11-06T15:24:01.748Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:01 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:01 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:01 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:02 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:02 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:02 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:02 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:02 dbus-daemon[1411]: [session uid=1000 pid=1411] Activating service name='org.gnome.gedit' requested by ':1.182' (uid=1000 pid=13314 comm="gjs /home/sabo/.local/share/gnome-shell/extensions")
ноя 06 17:24:02 dbus-daemon[1411]: [session uid=1000 pid=1411] Successfully activated service 'org.gnome.gedit'
ноя 06 17:24:02 gedit[15723]: Error loading plugin: libaspell.so.15: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
ноя 06 17:24:02 gedit[15723]: Error loading plugin: libnuspell.so.5: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
ноя 06 17:24:02 gedit[15723]: Error loading plugin: libvoikko.so.1: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
ноя 06 17:24:02 gedit[15723]: Error loading plugin: libhspell.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
ноя 06 17:24:02 gedit[15723]: Error loading plugin: libaspell.so.15: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
ноя 06 17:24:02 gedit[15723]: Error loading plugin: libnuspell.so.5: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
ноя 06 17:24:02 gedit[15723]: Error loading plugin: libvoikko.so.1: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
ноя 06 17:24:02 gedit[15723]: Error loading plugin: libhspell.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
ноя 06 17:24:02 gnome-shell[1540]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3e000e8
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.759Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15762
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.759Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 164f6364-e77a-4183-bd19-ced72ec637bf; GetAppSettings
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.760Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: ca551ae7-6b1b-40af-b592-1e85bc317557; GetAccount
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.760Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: ca551ae7-6b1b-40af-b592-1e85bc317557; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.760Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 92a75565-bc70-4cb1-aa73-2fc95f7d6066; GetDaemonStatus
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.760Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.760Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.760Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 92a75565-bc70-4cb1-aa73-2fc95f7d6066; Success
ноя 06 17:24:02 warp-svc[661]: 2023-11-06T15:24:02.760Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.747Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15764
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: a470bf2f-8266-49d7-bd33-7b7d4fe7a50b; GetAppSettings
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: d23d8963-61ce-4baf-914f-e4fb1bc62378; GetAccount
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: d23d8963-61ce-4baf-914f-e4fb1bc62378; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 0073eecf-d385-46b5-a3a2-68e30765be41; GetDaemonStatus
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.747Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 0073eecf-d385-46b5-a3a2-68e30765be41; Success
ноя 06 17:24:03 warp-svc[661]: 2023-11-06T15:24:03.748Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.408Z DEBUG warp::warp_service::network_change: Routes changed:
ноя 06 17:24:04 warp-svc[661]: NewNeighbour; Destination: 192.168.50.1;
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.410Z DEBUG warp::warp_service::network_change: Routes changed:
ноя 06 17:24:04 warp-svc[661]: NewNeighbour; Destination: 192.168.50.1;
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.749Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15766
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.749Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: e275d4a0-5a1e-4b16-a6d6-262994ebed5e; GetAppSettings
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.749Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 944c4ef3-bf26-4a0e-981c-cc9480dd4850; GetAccount
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.749Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 944c4ef3-bf26-4a0e-981c-cc9480dd4850; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.749Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: ac3331f3-23bd-459c-89a2-dfa29b41d143; GetDaemonStatus
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.749Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.749Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.749Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: ac3331f3-23bd-459c-89a2-dfa29b41d143; Success
ноя 06 17:24:04 warp-svc[661]: 2023-11-06T15:24:04.750Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.767Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15768
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.767Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 4ea9bbfd-8e38-43e3-9a44-9f75b697edd8; GetAppSettings
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.767Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 29d01811-e5a6-4eff-82fa-75ded0691ce2; GetAccount
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.767Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 29d01811-e5a6-4eff-82fa-75ded0691ce2; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.768Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: a5c6f435-463d-48a5-9cc8-a29b16005878; GetDaemonStatus
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.768Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.768Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.768Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: a5c6f435-463d-48a5-9cc8-a29b16005878; Success
ноя 06 17:24:05 warp-svc[661]: 2023-11-06T15:24:05.768Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.770Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15769
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 6a2ca66d-e1ab-4e20-896f-92539d00a0fe; GetAppSettings
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: d166877e-ce35-46ea-a551-9a63ed65a4b1; GetAccount
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.771Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: d166877e-ce35-46ea-a551-9a63ed65a4b1; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.771Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: d4a09b0f-f42d-4f5f-b020-8e63450c9ae3; GetDaemonStatus
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.771Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.771Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.771Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: d4a09b0f-f42d-4f5f-b020-8e63450c9ae3; Success
ноя 06 17:24:06 warp-svc[661]: 2023-11-06T15:24:06.771Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.769Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15771
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: b3d2834a-a36c-4832-93ef-e3a69a5cc322; GetAppSettings
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: f074a06f-b1a3-47ba-a9e2-8349d12adfe2; GetAccount
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: f074a06f-b1a3-47ba-a9e2-8349d12adfe2; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 8e1ab2ca-9a06-4fdd-be74-fdc899dc7cc1; GetDaemonStatus
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 8e1ab2ca-9a06-4fdd-be74-fdc899dc7cc1; Success
ноя 06 17:24:07 warp-svc[661]: 2023-11-06T15:24:07.771Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.769Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15773
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.769Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: dc764f03-840a-4d2b-9af8-d8eaa09b6e03; GetAppSettings
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.769Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 9c193759-6c15-4457-9e6d-096d73bcb9d2; GetAccount
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.769Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 9c193759-6c15-4457-9e6d-096d73bcb9d2; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: bd49c904-acc9-4867-a300-67755e6209c4; GetDaemonStatus
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.770Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: bd49c904-acc9-4867-a300-67755e6209c4; Success
ноя 06 17:24:08 warp-svc[661]: 2023-11-06T15:24:08.770Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.784Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15778
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.784Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 61e4a4c3-9f4a-4c8a-bc71-4b24a7a82a4c; GetAppSettings
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.784Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 71c3018f-9ecf-47df-a753-52d3f6c3c6d4; GetAccount
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.784Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 71c3018f-9ecf-47df-a753-52d3f6c3c6d4; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.785Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 5145bff3-3380-43d3-8944-220873d46aff; GetDaemonStatus
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.785Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.785Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.785Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 5145bff3-3380-43d3-8944-220873d46aff; Success
ноя 06 17:24:09 warp-svc[661]: 2023-11-06T15:24:09.785Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.785Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15780
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.785Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: b896f954-87e5-4d4e-841c-ac78bf2a20ca; GetAppSettings
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.786Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: dba72bce-46d4-49c6-b57e-0c3a62cecdff; GetAccount
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.786Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: dba72bce-46d4-49c6-b57e-0c3a62cecdff; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.786Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 20cc8b5f-08a2-49ed-9ba6-444f7ec80e39; GetDaemonStatus
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.786Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.786Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.786Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 20cc8b5f-08a2-49ed-9ba6-444f7ec80e39; Success
ноя 06 17:24:10 warp-svc[661]: 2023-11-06T15:24:10.786Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.787Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15784
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.787Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 9b3cdfc4-dcf7-4a56-a898-2424d045ee3b; GetAppSettings
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: b91733f8-0361-45bb-86aa-6c38f8b632c2; GetAccount
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: b91733f8-0361-45bb-86aa-6c38f8b632c2; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 6d421dca-6fad-46cf-bd92-6d18290d257f; GetDaemonStatus
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 6d421dca-6fad-46cf-bd92-6d18290d257f; Success
ноя 06 17:24:11 warp-svc[661]: 2023-11-06T15:24:11.788Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.788Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15785
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: b29b2b30-74db-4ff8-985d-e3618550bf78; GetAppSettings
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 8e197b24-1b42-4343-a2be-8d9239379af5; GetAccount
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.788Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 8e197b24-1b42-4343-a2be-8d9239379af5; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.789Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 359e1abf-b687-40bf-8c74-f4d8f2f151d5; GetDaemonStatus
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.789Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.789Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.789Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 359e1abf-b687-40bf-8c74-f4d8f2f151d5; Success
ноя 06 17:24:12 warp-svc[661]: 2023-11-06T15:24:12.789Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.775Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15786
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.775Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 78617ce8-f009-4ca3-9eed-fb156fcdeb8e; GetAppSettings
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.775Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: e62545c6-cd03-4eae-9b41-efffb02d3aa5; GetAccount
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.775Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: e62545c6-cd03-4eae-9b41-efffb02d3aa5; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.775Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: d0a11b8e-6668-4c6b-95c8-197968db70b0; GetDaemonStatus
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.775Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.775Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.775Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: d0a11b8e-6668-4c6b-95c8-197968db70b0; Success
ноя 06 17:24:13 warp-svc[661]: 2023-11-06T15:24:13.776Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.792Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15788
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.792Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 2318cb24-21ff-4002-9afa-0543d4880eb5; GetAppSettings
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.792Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: c1121c56-1353-45ae-b02f-5fbd1857f564; GetAccount
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.792Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: c1121c56-1353-45ae-b02f-5fbd1857f564; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.793Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: b17b0947-da4a-46c9-835b-319d6c5d2deb; GetDaemonStatus
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.793Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.793Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.793Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: b17b0947-da4a-46c9-835b-319d6c5d2deb; Success
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.793Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:14 warp-svc[661]: 2023-11-06T15:24:14.883Z DEBUG boringtun::noise::timers: SESSION_EXPIRED(REJECT_AFTER_TIME) session=10955030 index=42793
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15790
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 25a4e74d-55a1-4e37-bfea-55be254285c0; GetAppSettings
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: fbad16c5-d0d6-48ae-b3b7-e1b5b95950a0; GetAccount
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: fbad16c5-d0d6-48ae-b3b7-e1b5b95950a0; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: 8b9a0ef5-1f96-46eb-bdf9-30d38b9855dc; GetDaemonStatus
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: 8b9a0ef5-1f96-46eb-bdf9-30d38b9855dc; Success
ноя 06 17:24:15 warp-svc[661]: 2023-11-06T15:24:15.782Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:16 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:16 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.800Z  INFO warp::warp_service::ipc_loop: IPC: new connection privileged=false process_name="/usr/bin/warp-cli" pid=15794
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.800Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: fb302fa4-e381-43dd-8eb0-3af7e56a8da0; GetAppSettings
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.801Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: d7cfdf5a-dd5b-4e0e-a58a-69553857cbf6; GetAccount
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.801Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: d7cfdf5a-dd5b-4e0e-a58a-69553857cbf6; Registration: ID: ff607839-9979-4c5a-acf9-82f924b63805; Public Key: 59f0a4cd659149e67ed48f71192e6bcc6e3ed31a904ff3fc829579b073883d4e; Managed: false; Account: Free { id: AccountId(1f83be96-70b6-4ac2-8823-4575a56d041a), license: "2lm10Nh9-tb7F306G-vJ65BL73" };
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.801Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc request: a17bfe22-0ea5-4d05-a2d9-6810de88840b; GetDaemonStatus
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.801Z DEBUG main_loop: warp::warp_service::ipc_handlers: Sending IPC status update: Connected
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.801Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc Broadcast ResponseStatus: Connected
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.801Z DEBUG main_loop: warp::warp_service::ipc_handlers: Ipc response: a17bfe22-0ea5-4d05-a2d9-6810de88840b; Success
ноя 06 17:24:16 warp-svc[661]: 2023-11-06T15:24:16.801Z  INFO warp::warp_service::ipc_loop: IPC connection ended
ноя 06 17:24:16 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:16 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:17 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:17 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:_readLoop:364]: Redmi Note 8 Pro: {
                                                                  "id": 1699284256265,
                                                                  "type": "kdeconnect.mousepad.request",
                                                                  "body": {
                                                                    "dx": 0,
                                                                    "dy": 0
                                                                  }
                                                                }
ноя 06 17:24:17 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:17 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:_readLoop:364]: Redmi Note 8 Pro: {
                                                                  "id": 1699284256281,
                                                                  "type": "kdeconnect.mousepad.request",
                                                                  "body": {
                                                                    "dx": 18,
                                                                    "dy": -219
                                                                  }
                                                                }
ноя 06 17:24:17 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/components/ydotool.js:set args:81]: ydotool,mousemove,--,18,-219: Не удалось выполнить дочерний процесс "ydotool" (Нет такого файла или каталога)
                                                                set args@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/ydotool.js:81:28
                                                                movePointer@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/ydotool.js:93:59
                                                                _handleInput@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mousepad.js:206:29
                                                                handlePacket@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mousepad.js:172:22
                                                                handlePacket@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:441:25
                                                                _readLoop@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:365:22
                                                                async*setChannel@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:346:18
                                                                _onChannel@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:229:20
                                                                channel@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:436:19
                                                                _onIncomingChannel@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:244:18
                                                                async*@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:720:17
ноя 06 17:24:17 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:handlePacket:443]: Redmi Note 8 Pro: "Unsupported packet type (kdeconnect.sms.messages)"
ноя 06 17:24:17 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/device.js:_readLoop:364]: Redmi Note 8 Pro: {
                                                                  "id": 1699284256298,
                                                                  "type": "kdeconnect.mousepad.request",
                                                                  "body": {
                                                                    "dx": 10,
                                                                    "dy": -208
                                                                  }
                                                                }
ноя 06 17:24:17 org.gnome.Shell.Extensions.GSConnect[13834]: [/service/components/ydotool.js:set args:81]: ydotool,mousemove,--,10,-208: Не удалось выполнить дочерний процесс "ydotool" (Нет такого файла или каталога)
                                                                set args@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/ydotool.js:81:28
                                                                movePointer@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/ydotool.js:93:59
                                                                _handleInput@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mousepad.js:206:29
                                                                handlePacket@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mousepad.js:172:22
                                                                handlePacket@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:441:25
                                                                _readLoop@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:365:22
                                                                async*setChannel@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:346:18
                                                                _onChannel@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:229:20
                                                                channel@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:436:19
                                                                _onIncomingChannel@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:244:18
                                                                async*@/home/sabo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:720:17
```

### Screenshots

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by JingMatrix**
The environment variable GNOME_SETUP_DISPLAY is not reliably set since GNOME 45.
We revert to use `imports.ui` for detecting method of GNOME environment. Fix #1706

### CODE REVIEW

**Comment by JingMatrix** [comment]
Since for cli usage, there is no need to install the `gnome-shell`
package, we may thus use `imports.gi.Shell` as heuristic for detecting the
GNOME environment. As a fallback, the user can deliberately set up the
`GSCONNECT_MODE` environment variable to be `cli` to claim the cli
environment.

File: src/service/utils/setup.js [hunk 1]
```diff
@@ -105,7 +105,13 @@ for (const path of [Config.CACHEDIR, Config.CONFIGDIR, Config.RUNTIMEDIR])
  */
 globalThis.HAVE_REMOTEINPUT = GLib.getenv('GDMSESSION') !== 'ubuntu-wayland';
 globalThis.HAVE_WAYLAND = GLib.getenv('XDG_SESSION_TYPE') === 'wayland';
-globalThis.HAVE_GNOME = GLib.getenv('GNOME_SETUP_DISPLAY') !== null;
+globalThis.HAVE_GNOME = GLib.getenv('GSCONNECT_MODE') !== 'cli';
+try {
+    // eslint-disable-next-line no-unused-expressions
+    imports.gi.Shell;
```
Comment (andyholmes) [inline src/service/utils/setup.js:111]: Like `imports.ui`, this will always fail because `imports.gi.Shell` is a private library only available in the `gnome-shell` process.

I'd suggest using the env variable [`XDG_SESSION_DESKTOP`](https://www.freedesktop.org/software/systemd/man/latest/pam_systemd.html#Environment) and checking for [`GNOME`](https://specifications.freedesktop.org/menu-spec/latest/apb.html). This should be exported for all GNOME users:

```sh
$ echo $XDG_CURRENT_DESKTOP 
GNOME
```

**Review by andyholmes — CHANGES_REQUESTED** [review]

File: src/service/utils/setup.js (hunk 1 above)
Comment (JingMatrix) [reply src/service/utils/setup.js:111]: In this [Arch Wiki page](https://wiki.archlinux.org/title/environment_variables), it is said that `XDG_SESSION_DESKTOP`  is not standardized by freedesktop.org, with a link to the issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/1224#note_270915

**Comment by andyholmes** [comment]
Thanks for the fix @JingMatrix!

**Comment by StephGbzh** [comment]
I just updated my system to Ubuntu 23.10 and the variables have the following values:

```bash
> echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
> echo $XDG_SESSION_DESKTOP
ubuntu
```

If my understanding of js syntax is correct, the new code will still NOT detect Gnome in this case.

```js
GLib.getenv('XDG_CURRENT_DESKTOP')?.toUpperCase() === 'GNOME' || GLib.getenv('XDG_SESSION_DESKTOP')?.toLowerCase() === 'gnome')
```
