### PR TITLE
Use GioUnix for GNOME 46

### LINKED ISSUE #1781: nightly noncritical error on gnome 46
### Describe the bug

When starting up journalctl shows the following uncritical error:

`gjs: Gio.UnixInputStream has been moved to a separate platform-specific library. Please update your code to use GioUnix.InputStream instead.
                                   0 _initUdpListener() ["/home/harvey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js":267:16]
                                   1 start() ["/home/harvey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js":458:21]
                                   2 _loadBackends() ["/home/harvey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js":259:24]
                                   3 start() ["/home/harvey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js":462:13]
                                   4 vfunc_startup() ["/home/harvey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js":263:21]
                                   5 vfunc_handle_local_options() ["/home/harvey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js":660:17]
                                   6 <TOP LEVEL> ["/home/harvey/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js":720:16]`

### Steps to reproduce

journalctl -b -p4

### Expected behavior

_No response_

### GSConnect version

56 nightly 2024-April-04

### Installed from

GitHub releases (zip file)

### GNOME Shell version

46

### Linux distribution/release

Arch

### Paired device(s)

OnePlus IN2023

### KDE Connect app version

1.29.0

### Plugin(s)

_No response_

### Support log

_No response_

### Screenshots

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by ferdnyc**
Seems `Gio` has been fragmented, its platform-specific classes are now part of a separate [`GioUnix`](https://docs.gtk.org/gio-unix/index.html) library.

Fixes #1781

### CODE REVIEW

**Comment by ferdnyc** [comment]
I suspect our CI image needs to be updated to include the `GioUnix` library.

Test log file `gsconnect_plugins_testSftpPlugin.test.txt`:
```text
(gjs:406): Gjs-CRITICAL **: 11:36:48.325: JS ERROR: 
Error: Requiring GioUnix, version none: 
Typelib file for namespace 'GioUnix' (any version) not found
@/usr/libexec/installed-tests/gsconnect/fixtures/backend.js:8:17
@/usr/libexec/installed-tests/gsconnect/fixtures/utils.js:33:26
@/usr/libexec/installed-tests/gsconnect/plugins/testSftpPlugin.js:7:15
initTests@/usr/libexec/installed-tests/gsconnect/minijasmine:128:5
@/usr/libexec/installed-tests/gsconnect/minijasmine:162:1


(gjs:406): Gjs-CRITICAL **: 11:36:48.325: 
Script /usr/libexec/installed-tests/gsconnect/minijasmine 
threw an exception
```

**Comment by ferdnyc** [comment]
Hmmm. Unfortunately, even in Fedora 39, GioUnix isn't available.

(`/usr/lib64/libgio-2.0.so.0` lives in the `glib2` package, `/usr/lib64/girepository-1.0/Gio-2.0.typelib` lives in `gobject-introspection`, and `/usr/share/gir-1.0/Gio-2.0.gir` lives in `gobject-introspection-devel`, but none of those include `GioUnix` in Fedora 39. Presumably Fedora 40 will have it available, but that's still in beta so I don't think there are Docker images yet. This may have to wait until release. ...Which is soon, so NBD.)

**Comment by andyholmes** [comment]
Ah right, I forgot about this. It's purely a namespace change in terms of API, so if necessary I think polyfill/alias can be used.

https://gitlab.gnome.org/GNOME/gjs/blob/83003b6c4781735818f195da7c2cb61059bcd4c1/installed-tests/js/testGDBus.js#L7-L15

```js
// Adapter for compatibility with pre-GLib-2.80
let GioUnix;
if (imports.gi.versions.GioUnix === '2.0') {
    GioUnix = imports.gi.GioUnix;
} else {
    GioUnix = {
        InputStream: Gio.UnixInputStream,
    };
}
```

**Comment by ferdnyc** [comment]
@andyholmes That should work, plus `OutputStream` for `nativeMessagingHost.js`.

It's weird, though, that running under the new CI image didn't fix this — I even see in the Meson logs that it's GLib 2.80, so that should have `GioUnix` available. I even checked on koji earlier that its `.gir` and `.typelib` files are included in the F40 `gobject-introspection[-devel]` RPMs.

Maybe I'll pull the new CI image locally and take a look.

**Comment by andyholmes** [comment]
Yeah, my local `fedora-toolbox:40` definitely has it, and I double-checked the container hash with the `GSConnect/gsconnect-ci:main` hash. :thinking:

File: src/service/backends/lan.js [hunk 1]
```diff
@@ -5,6 +5,7 @@
 'use strict';
 
 const Gio = imports.gi.Gio;
+const GioUnix = imports.GioUnix;
```
Comment (ferdnyc) [inline src/service/backends/lan.js:8]: Duhhhhhhhh.

```suggestion
const GioUnix = imports.gi.GioUnix;
```

**Review by ferdnyc — COMMENTED** [review]
Well, I'm glad I did that, because I discovered that the image is missing `dbus-devel`, oddly enough — guess it's not pulled in as a dependency anymore. So I'll have to fix the Dockerfile over there.

But the _extension_ is broken, specifically, because of this boneheaded code.

File: src/service/backends/lan.js (hunk 1 above)
Comment (ferdnyc) [reply src/service/backends/lan.js]: I suppose it would be better to still do the polyfill thing.

**Comment by ferdnyc** [comment]
Un-marking this as WIP because it _could_ be merged now, though for the record I am planning on updating the `GioUnix` uses to take a "polyfill" approach to loading.

But if anyone's getting impatient and doesn't feel like waiting for that change, this _could_ now go in as-is, since the CI image is updated to GNOME 46 and builds are once again in the green.

**Comment by andyholmes** [comment]
Either way is fine, it's not critical either way. Merge when ready :)

**Review by daniellandau — APPROVED** [review]
This looks good to me. I didn't have time to test locally and didn't quite follow the logic of the hesitation discussion but let's get this in before the release if there's no pressing reason not to.

**Comment by ferdnyc** [comment]
@andyholmes

Ooh, actually, I don't see how this would work:

> ```js
> // Adapter for compatibility with pre-GLib-2.80
> let GioUnix;
> if (imports.gi.versions.GioUnix === '2.0') {
>     GioUnix = imports.gi.GioUnix;
> } else {
>     GioUnix = {
>         InputStream: Gio.UnixInputStream,
>     };
> }
> ```

My code _is **setting**_ `imports.gi.versions.GioUnix = '2.0';` early on in `daemon.js`, since that's the (weird) method gobject-introspection uses to do version selection. So the condition's always going to be true.

Would a try/catch be a safer approach? Testing in the `gjs` console, it seems to work:

```javascript
let GioUnix;
try {
    GioUnix = imports.gi.GioUnix;
} catch (e) {
    GioUnix = {
        InputStream: Gio.UnixInputStream,
        OutputStream: Gio.UnixOutputStream,
    };
}
```

**Comment by andyholmes** [comment]
Actually, it might be good to have @retrixe weigh in here, since a polyfill/alias might need another approach for ESModules.

**Comment by andyholmes** [comment]
> Ooh, actually, I don't see how this would work:


Hmm, actually for old-school imports i be this would work:

```js
let GioUnix = null;
try {
    GioUnix = imports.gi.GioUnix;
} catch {
    GioUnix = imports.gi.Gio;
}
```

The versioning probably isn't necessary; I think it's questionable whether there will ever be a another major revision of the GLib/GObject/Gio and there certainly isn't now.

**Comment by ferdnyc** [comment]
> Hmm, actually for old-school imports I bet this would work:
> 
> ```js
> let GioUnix = null;
> try {
>     GioUnix = imports.gi.GioUnix;
> } catch {
>     GioUnix = imports.gi.Gio;
> }
> ```

Alas, nope. The member names are `UnixInputStream` and `UnixOutputStream` in `Gio` but `InputStream` and `OutputStream` in `GioUnix`.

**Comment by andyholmes** [comment]
Ah, disappointing :(

**Comment by retrixe** [comment]
For ESM, we would need to use dynamic imports with top level await in a try/catch 

For specifying the version, we could either specify the version every time we import it, or use dynamic import in try/catch where we currently set the version

**Comment by ferdnyc** [comment]
Don't ask me how I copy-pasted a block of code to three files, yet managed to leave out a space in only _one_ of them.

**Comment by andyholmes** [comment]
This looks good to merge from my side, whenever you're ready.

I'd suggest we merge this before #1683, so there's a commit to branch/release off of if necessary.

**Comment by ferdnyc** [comment]
Sorry, was asleep at the wheel. Trigger pulled.
