### PR TITLE
Cleanup/fix notification code for GNOME 46

### LINKED ISSUE #1775: Incoming call notification is staying always visible and notification buttons not working
### Describe the bug

After getting a call notification, the notification will always stay there. (Screenshots is below)

The only way to hide the notification is logging out from Gnome session.

### Steps to reproduce

1. Connect your KDEConnect application in Android and GSConnect extension.
2. Allow KDEConnect to handling incoming calls
3. Call the phone that connected via KDEConnect.
4. GSConnect will show the incoming call notification.
5. And there are no way to hide. Clicking buttons (including (X) and (^) buttons that placed top right of notification), answering the call, ignoring the call is not a solution.

### Expected behavior

It hides the incoming call notifications.

### GSConnect version

56 (Installed from Nightly Builds from Github)

### Installed from

GitHub releases (zip file)

### GNOME Shell version

46

### Linux distribution/release

Arch Linux

### Paired device(s)

Samsung A11

### KDE Connect app version

1.29.0

### Plugin(s)

Call notifier

### Support log

_No response_

### Screenshots

image
image

### Notes

_No response_

### PR DESCRIPTION
**Pull request by DaPigGuy**
Fixes #1775 
Fixes https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1771#discussion_r1546133301

### CODE REVIEW

**Review by daniellandau — APPROVED** [review]
Looks good, awesome thanks!

File: src/shell/notification.js [hunk 1]
```diff
@@ -252,50 +246,86 @@ const Source = GObject.registerClass({
...
+
+        const createdNotification = this._createNotification(notification);
+        this._addNotificationToMessageTray(createdNotification);
+
+        this._notificationPending = false;
+    }
+
+    /*
+     * Reimplementation of MessageTray.addNotification to raise the usual
+     * notification limit (3)
```
Comment (ferdnyc) [inline src/shell/notification.js:304]: (Belatedly, sorry... but...)

I wonder if this is a good idea? Just because, GNOME could _change_ the notification limit from `3` tomorrow, and then the comment's wrong. The more important point is probably that we raise it _to_ `10`.

I mean, it's just a comment, so it's not worth a PR just to change it anyway.
